/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ebank.view;
import br.com.ebank.business.BCliente;
import br.com.ebank.business.BConta;
import br.com.ebank.business.BUsuario;
import br.com.ebank.entity.Cliente;
import br.com.ebank.entity.Conta;
import br.com.ebank.entity.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author internet
 */
public class TP_Adm extends javax.swing.JFrame {
private String login;
private String senha;
int n;

public boolean campoVazioUsu(){
    if (txtEndereco.getText().equals("")||
            txtRg.getText().equals("")||
            txtCpf.getText().equals("")||
            txtNome.getText().equals(""))
        return true;
    else
        return false;
}
public void desabilitarTxts(){
    txtNome.setEnabled(false);
    txtRg.setEnabled(false);
    txtCpf.setEnabled(false);
    txtEndereco.setEnabled(false);
    txtSenha.setEnabled(false);
}

public void habilitarTxts(){
    txtNome.setEnabled(true);
    txtRg.setEnabled(true);
    txtCpf.setEnabled(true);
    txtEndereco.setEnabled(true);
    txtSenha.setEnabled(true);
}

public void trazerTxts(){
            txtSenha.setVisible(true);
            txtEndereco.setVisible(true);
            txtRg.setVisible(true);
            txtCpf.setVisible(true);
            txtNome.setVisible(true);
}
public void trazerTxtsUsu(){
            txtEndereco.setVisible(true);
            txtRg.setVisible(true);
            txtCpf.setVisible(true);
            txtNome.setVisible(true);
}

public void trazerLabels(){
    lblCsenha.setVisible(true);
            lblCendereco.setVisible(true);
            lblCrg.setVisible(true);
            lblCcpf.setVisible(true);
            lblCnome.setVisible(true);
}
public void sumirLabels(){
            lblCsenha.setVisible(false);
            lblCendereco.setVisible(false);
            lblCrg.setVisible(false);
            lblCcpf.setVisible(false);
            lblCnome.setVisible(false);
}
public void sumirTxts(){
            txtSenha.setVisible(false);
            txtEndereco.setVisible(false);
            txtRg.setVisible(false);
            txtCpf.setVisible(false);
            txtNome.setVisible(false);
}

public void limparLbl(){
    this.lblCcpf.setText("");
        this.lblCrg.setText("");
        this.lblCnome.setText("");
        this.lblCsenha.setText("");
        this.lblCendereco.setText("");
}
public void limparTxt(){
    this.txtCpf.setText("");
        this.txtRg.setText("");
        this.txtNome.setText("");
        this.txtSenha.setText("");
        this.txtEndereco.setText("");
}

public boolean campoVazio(){
    if (txtSenha.getText().equals("")||
            txtEndereco.getText().equals("")||
            txtRg.getText().equals("")||
            txtCpf.getText().equals("")||
            txtNome.getText().equals(""))
        return true;
    else
        return false;
}

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
    
    /**
     * Creates new form FRMClliente
     */
    public TP_Adm() {
        initComponents();
        btnAlterar.setEnabled(false);
        btnSalvar.setVisible(false);
        this.btnNovo.setVisible(false);
        this.btnExcluir.setEnabled(false);
        this.lblUsuEmail.setVisible(false);
        this.lblUsuLogin.setVisible(false);
        this.lblUsuSenha.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtRg = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblCnome = new javax.swing.JLabel();
        lblCrg = new javax.swing.JLabel();
        lblCcpf = new javax.swing.JLabel();
        lblCendereco = new javax.swing.JLabel();
        lblCsenha = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnAlteraSenha = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlternar = new javax.swing.JToggleButton();
        lblUsuEmail = new javax.swing.JLabel();
        lblUsuLogin = new javax.swing.JLabel();
        lblUsuSenha = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 70, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Rg:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 40, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("CPF:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 60, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Endereço:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 100, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 301, -1));
        getContentPane().add(txtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 301, -1));
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 301, -1));
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 301, -1));

        btnCadastrar.setBackground(new java.awt.Color(0, 51, 255));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 110, -1));

        btnBuscar.setBackground(new java.awt.Color(0, 51, 255));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 105, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Senha:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 301, -1));

        btnAlterar.setBackground(new java.awt.Color(0, 51, 255));
        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 105, -1));

        btnSair.setBackground(new java.awt.Color(153, 0, 0));
        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 660, 90, -1));

        lblCnome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(lblCnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 300, 20));

        lblCrg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(lblCrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 300, 20));

        lblCcpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(lblCcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 300, 19));

        lblCendereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(lblCendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 400, 20));

        lblCsenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(lblCsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 300, 21));

        btnSalvar.setBackground(new java.awt.Color(0, 51, 255));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 110, -1));

        btnAlteraSenha.setBackground(new java.awt.Color(153, 0, 0));
        btnAlteraSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAlteraSenha.setForeground(new java.awt.Color(255, 255, 255));
        btnAlteraSenha.setText("Alterar minha senha");
        btnAlteraSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlteraSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 620, 180, -1));

        btnNovo.setBackground(new java.awt.Color(0, 51, 255));
        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 110, -1));

        btnLista.setBackground(new java.awt.Color(0, 51, 255));
        btnLista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLista.setForeground(new java.awt.Color(255, 255, 255));
        btnLista.setText("Lista ");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 105, -1));

        btnExcluir.setBackground(new java.awt.Color(0, 51, 255));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 105, -1));

        btnAlternar.setText("Administrar Usuarios");
        btnAlternar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlternarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlternar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 650, 180, -1));

        lblUsuEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUsuEmail.setForeground(new java.awt.Color(102, 102, 255));
        lblUsuEmail.setText("Email:");
        getContentPane().add(lblUsuEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 80, -1));

        lblUsuLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUsuLogin.setForeground(new java.awt.Color(102, 102, 255));
        lblUsuLogin.setText("Login:");
        getContentPane().add(lblUsuLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 60, -1));

        lblUsuSenha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUsuSenha.setForeground(new java.awt.Color(102, 102, 255));
        lblUsuSenha.setText("Senha:");
        getContentPane().add(lblUsuSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Account Edition");
        jPanel1.add(jLabel5);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 610, 530));

        lblImg.setBackground(new java.awt.Color(255, 0, 0));
        lblImg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblImg.setForeground(new java.awt.Color(255, 255, 255));
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ebank/view/imgFundoFrmAdm.jpg"))); // NOI18N
        getContentPane().add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        if(this.btnAlternar.isSelected()){//Usuario
          //  (int id, String nome, String login, String email, String senha)
            if(this.campoVazioUsu()){
                JOptionPane.showMessageDialog(null, String.format("Por favor preencha todos os campos!"));
            }
            else{
             Usuario usuario = new Usuario(0, this.txtNome.getText(), this.txtRg.getText(), this.txtCpf.getText(), this.txtEndereco.getText());
             //testeJOptionPane.showMessageDialog(null,String.format("Criado:\n%s\nNome: %s\nlogin: %s\nemail: %s\nsenha: %s", Integer.toString(usuario.getId()), usuario.getNome(), usuario.getLogin(),usuario.getEmail(),usuario.getSenha()));
             BUsuario busuario = new BUsuario();
             if(busuario.cadastrar(usuario)){
                JOptionPane.showMessageDialog(null, String.format("Usuário cadastrado com sucesso."));
                this.limparTxt();
             }
            else{
              JOptionPane.showMessageDialog(null, String.format("Não foi possível cadastrar o usuário"));  
            }
        }
        }
        else{
            if (this.campoVazio())
                JOptionPane.showMessageDialog(null,String.format("Por favor preencha todos os campos!"));
            else{//conta e cliente
            
        BConta bconta = new BConta();
        Conta conta = new Conta(Integer.parseInt(txtSenha.getText()));
        //
         BCliente bcli = new BCliente();
        Cliente cli = new Cliente(txtNome.getText(),txtRg.getText(),txtCpf.getText(),txtEndereco.getText());
        // 
        if(bconta.cadastrar(conta) && bcli.cadastrar(cli)){
            try {
                JOptionPane.showMessageDialog(null,String.format("Cadastro realizado com sucesso.\nConta n° : %d", (bconta.pegaNumero(txtCpf.getText()).getNumero())));
                this.limparTxt();
                this.btnNovo.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(TP_Adm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null,String.format("Não foi possível fazer o cadastro."));
        }
            }
        }
        
        //else{
           
           // }
            
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         //TODO add your handling code here:
          
        this.btnSalvar.setVisible(false);   
         if (btnAlternar.isSelected()){
           n=Integer.parseInt(JOptionPane.showInputDialog("Digite o id do usuario"));  
          BUsuario busuario = new BUsuario();
          if(busuario.buscarUsuario(n).getNome()==null){
              JOptionPane.showMessageDialog(null,String.format("Usuario não encontrado."));
              this.desabilitarTxts();
          }
          else{
              //this.sumirLabels();
              btnCadastrar.setVisible(false);
              btnNovo.setVisible(true);
              this.btnExcluir.setEnabled(true);
              lblCsenha.setVisible(false);
              lblCendereco.setText(busuario.buscarUsuario(n).getSenha());
              lblCrg.setText(busuario.buscarUsuario(n).getLogin());
              lblCcpf.setText(busuario.buscarUsuario(n).getEmail());
              lblCnome.setText(busuario.buscarUsuario(n).getNome());
              this.lblCnome.setVisible(true);
              this.lblCrg.setVisible(true);
              this.lblCcpf.setVisible(true);
              this.lblCendereco.setVisible(true);
              this.btnNovo.setVisible(true);
              this.sumirTxts();
              btnAlterar.setEnabled(true);
              this.btnNovo.setVisible(true);
              this.btnNovo.setEnabled(true);
          }
         }
         
         
         else{  
 
        n=Integer.parseInt(JOptionPane.showInputDialog("Digite o numero da conta"));
        BConta bconta = new BConta();
        try {
            
            if(bconta.buscar(n).getSenha()==0){
                JOptionPane.showMessageDialog(null,String.format("Conta não encontrada."));
            this.desabilitarTxts();
            }
            else{
            btnCadastrar.setVisible(false);
            btnNovo.setVisible(true);
            this.btnExcluir.setEnabled(true);
            lblCsenha.setText(Integer.toString(bconta.buscar(n).getSenha()));
            lblCendereco.setText(bconta.buscarTitular(n).getEndereco());
            lblCrg.setText(bconta.buscarTitular(n).getRg());
            lblCcpf.setText(bconta.buscarTitular(n).getCpf());
            lblCnome.setText(bconta.buscarTitular(n).getNome());
            this.sumirTxts();
            this.trazerLabels();
            this.btnNovo.setVisible(true);
            
            btnAlterar.setEnabled(true);
            this.btnNovo.setVisible(true);
            this.btnNovo.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TP_Adm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        if(btnAlternar.isSelected()){
        btnAlterar.setEnabled(false);
        btnCadastrar.setVisible(false);
        btnSalvar.setVisible(true);
        this.sumirLabels();
        //txtSenha.setVisible(true);
        txtSenha.setText(lblCsenha.getText());
        txtSenha.setEnabled(true);
        txtEndereco.setVisible(true);
        txtEndereco.setText(lblCendereco.getText());
        txtEndereco.setEnabled(true);
        txtRg.setVisible(true);
        txtRg.setText(lblCrg.getText());
        txtRg.setEnabled(true);
        txtCpf.setVisible(true);
        txtCpf.setText(lblCcpf.getText());
        txtCpf.setEnabled(true);
        txtNome.setVisible(true);
        txtNome.setText(lblCnome.getText());
        txtNome.setEnabled(true);
        btnCadastrar.setEnabled(false);
        }
        else{
        btnAlterar.setEnabled(false);
        btnCadastrar.setVisible(false);
        btnSalvar.setVisible(true);
        this.sumirLabels();
        txtSenha.setVisible(true);
        txtSenha.setText(lblCsenha.getText());
        txtSenha.setEnabled(true);
        txtEndereco.setVisible(true);
        txtEndereco.setText(lblCendereco.getText());
        txtEndereco.setEnabled(true);
        txtRg.setVisible(true);
        txtRg.setText(lblCrg.getText());
        txtRg.setEnabled(true);
        txtCpf.setVisible(true);
        txtCpf.setText(lblCcpf.getText());
        txtCpf.setEnabled(true);
        txtNome.setVisible(true);
        txtNome.setText(lblCnome.getText());
        txtNome.setEnabled(true);
        btnCadastrar.setEnabled(false);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (btnAlternar.isSelected()){
        //JOptionPane.showMessageDialog(null,Integer.toString(n));
        this.btnSalvar.setVisible(false);
        this.btnNovo.setVisible(false);
        this.btnCadastrar.setVisible(true);
        this.btnCadastrar.setEnabled(true);
        this.btnExcluir.setEnabled(false);
        Usuario usuario = new Usuario(0,this.txtNome.getText(),this.txtRg.getText(),this.txtCpf.getText(),this.txtEndereco.getText());
        //JOptionPane.showMessageDialog(null,String.format("nome: %s\n login: %s\n, email %s\nsenha%s\n", usuario.getNome(), usuario.getLogin(), usuario.getEmail(), usuario.getSenha()));
        if(new BUsuario().alterarUsuario(usuario, n)){
            JOptionPane.showMessageDialog(null,String.format("Usuario alterado com sucesso."));
            this.limparTxt();
        }
        else JOptionPane.showMessageDialog(null, String.format("Não foi possível salvar a alteração."));
        
        }
        else {
        BConta bconta = new BConta();
        BCliente bcliente = new BCliente();
        if(bconta.alterar(Integer.parseInt(txtSenha.getText()),n)){
        bcliente.alterar(txtNome.getText(), txtRg.getText(), txtCpf.getText(), txtEndereco.getText(), n);
        JOptionPane.showMessageDialog(null,String.format("Dados da conta alterados com sucesso."));
        this.btnExcluir.setEnabled(false);
        this.btnSalvar.setVisible(false);
        this.btnNovo.setVisible(false);
        this.limparTxt();
        this.btnCadastrar.setVisible(true);
        this.btnCadastrar.setEnabled(true);
        }
        else
          JOptionPane.showMessageDialog(null,String.format("Não foi possível salvar a alteração."));  
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaPrincipal telaprincipal = new TelaPrincipal();
        telaprincipal.montarJanela();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlteraSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraSenhaActionPerformed
        // TODO add your handling code here:
        String n =JOptionPane.showInputDialog("Digite sua senha Atual");
        if (n.equals(this.senha)){
           senha =JOptionPane.showInputDialog("Digite sua nova senha");
        BUsuario busuario = new BUsuario();
            try {
                busuario.alterarSenha(login,senha);
            } catch (SQLException ex) {
                Logger.getLogger(TP_Adm.class.getName()).log(Level.SEVERE, null, ex);
            }
        JOptionPane.showMessageDialog(null, String.format("Senha alterada com sucesso."));
        }
        else 
            JOptionPane.showMessageDialog(null,String.format("Senha incorreta."));
    }//GEN-LAST:event_btnAlteraSenhaActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        if (btnAlternar.isSelected()){
            this.btnNovo.setVisible(false);
        this.btnCadastrar.setVisible(true);
        this.btnCadastrar.setEnabled(true);
        this.btnAlterar.setEnabled(false);
        this.btnExcluir.setEnabled(false);
        this.limparTxt();
        
        this.txtCpf.setVisible(true);
        this.txtRg.setVisible(true);
        this.txtNome.setVisible(true);
        this.txtEndereco.setVisible(true);
        
        this.lblCcpf.setVisible(false);
        this.lblCrg.setVisible(false);
        this.lblCnome.setVisible(false);
        this.lblCsenha.setVisible(false);
        this.lblCendereco.setVisible(false);
        
        this.limparLbl();
        
        txtNome.setEnabled(true);
        txtRg.setEnabled(true);
        txtCpf.setEnabled(true);
        txtEndereco.setEnabled(true);
        
        }
        else {
        this.btnNovo.setVisible(false);
        this.btnExcluir.setEnabled(false);
        this.btnCadastrar.setVisible(true);
        this.btnCadastrar.setEnabled(true);
        this.btnAlterar.setEnabled(false);
        
        this.limparTxt();
        
        this.txtCpf.setVisible(true);
        this.txtRg.setVisible(true);
        this.txtNome.setVisible(true);
        this.txtSenha.setVisible(true);
        this.txtEndereco.setVisible(true);
        
        this.lblCcpf.setVisible(false);
        this.lblCrg.setVisible(false);
        this.lblCnome.setVisible(false);
        this.lblCsenha.setVisible(false);
        this.lblCendereco.setVisible(false);
        
        this.limparLbl();
        
        txtNome.setEnabled(true);
        txtRg.setEnabled(true);
        txtCpf.setEnabled(true);
        txtEndereco.setEnabled(true);
        txtSenha.setEnabled(true);
        
        
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        if (btnAlternar.isSelected()){
            TelaListaUsuarios tlusuarios = new TelaListaUsuarios();
            tlusuarios.setLocationRelativeTo(null);
           // tlusuarios.setSize(450,450);
            tlusuarios.exibirListaUsuarios();
            tlusuarios.setVisible(true);
        }
         /* BUsuario busuario = new BUsuario();
        int p = busuario.listaUsuario().size();
        String result="Lista de Usuários:\nId | Login \n";
        for (int i=0; i<p; i++){
            result += String.format("\n%s | %s ", busuario.listaUsuario().get(i).getId(),busuario.listaUsuario().get(i).getNome() );
        }
        JOptionPane.showMessageDialog(null, result);  
        }
            */
        else {
            
            TelaListaClientes tlclientes = new TelaListaClientes();
            tlclientes.exibirListaClientes();
            tlclientes.setLocationRelativeTo(null);
           // tlclientes.setSize(450,450);
            tlclientes.setVisible(true);
        /*BCliente bcliente = new BCliente();
        int p = bcliente.lista().size();
        String result="Lista de Clientes:\nConta | Nome \n";
        for (int i=0; i<p; i++){
            result += String.format("\n%s | %s ", bcliente.lista().get(i).getNumero(),bcliente.lista().get(i).getNome() );
        }
        JOptionPane.showMessageDialog(null, result);
       */
        }
       // bcliente.lista();
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if (btnAlternar.isSelected()){
            BUsuario busuario = new BUsuario();
            if(busuario.excluirUsuario(n)){
                JOptionPane.showMessageDialog(null,String.format("Usuario excluido com sucesso."));
                this.sumirLabels();
                this.limparLbl();
                this.trazerTxtsUsu();
                this.desabilitarTxts();
                this.btnAlterar.setEnabled(false);
            }
            else 
                JOptionPane.showMessageDialog(null,String.format("Não foi possível excluir o usuário"));
        }
        else{
        BConta bconta = new BConta();
        BCliente bcliente = new BCliente();
        if(bconta.excluirConta(n) && bcliente.excluirCliente(n)){
           // this.limparLbl();
            JOptionPane.showMessageDialog(null,String.format("Conta Excluída com sucesso."));
            this.desabilitarTxts();
            this.btnExcluir.setEnabled(false);
            this.btnAlterar.setEnabled(false);
            this.limparLbl();
            this.trazerTxts();
            
        }
        else 
            JOptionPane.showMessageDialog(null,String.format("Não foi possível excluir a conta"));
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlternarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlternarActionPerformed
        // TODO add your handling code here:     
       if(btnAlternar.isSelected()){
           this.trazerTxtsUsu();
           this.btnExcluir.setEnabled(false);
           this.btnAlternar.setText("Administrar Contas");
           this.limparTxt();
           this.jLabel2.setVisible(false);
           this.jLabel3.setVisible(false);
           this.jLabel4.setVisible(false);
           this.lblUsuEmail.setVisible(true);
           this.lblUsuLogin.setVisible(true);
           this.lblUsuSenha.setVisible(true);
           this.jLabel6.setVisible(false);
           this.txtSenha.setVisible(false);
           this.jLabel5.setText("User Edition");
           this.sumirLabels();
           this.btnCadastrar.setVisible(true);
           btnCadastrar.setEnabled(true);
           this.habilitarTxts();
           btnAlterar.setEnabled(false);
       }
       else{
           this.jLabel5.setText("Account Edition");
           this.btnAlternar.setText("Administrar Usuários");
           this.trazerTxts();
           this.btnExcluir.setEnabled(false);
           this.limparTxt();
           this.jLabel2.setVisible(true);
           this.jLabel3.setVisible(true);
           this.jLabel4.setVisible(true);
           this.lblUsuEmail.setVisible(false);
            this.lblUsuLogin.setVisible(false);
            this.lblUsuSenha.setVisible(false);
            this.jLabel6.setVisible(true);
            this.txtSenha.setVisible(true);
            this.sumirLabels();
            this.btnCadastrar.setVisible(true);
            this.btnCadastrar.setEnabled(true);
            this.habilitarTxts();
            btnAlterar.setEnabled(false);
       }
    }//GEN-LAST:event_btnAlternarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TP_Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TP_Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TP_Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TP_Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TP_Adm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlteraSenha;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JToggleButton btnAlternar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCcpf;
    private javax.swing.JLabel lblCendereco;
    private javax.swing.JLabel lblCnome;
    private javax.swing.JLabel lblCrg;
    private javax.swing.JLabel lblCsenha;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblUsuEmail;
    private javax.swing.JLabel lblUsuLogin;
    private javax.swing.JLabel lblUsuSenha;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
